/**
 * Downloads the four type families Tome uses into public/fonts/ as woff2 and
 * writes public/fonts/fonts.css (@font-face blocks, latin subset only).
 *
 * Run once, at authoring time — never at runtime. The Next app itself uses
 * next/font/google, which self-hosts the same files during `next build`; these
 * copies exist so the standalone pages under public/viz/ can be styled without
 * any request leaving the site.
 *
 * All four are variable fonts, so each family is one file covering the whole
 * weight range Tome asks for.
 *
 *   node scripts/fetch-fonts.mjs
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const OUT = path.join(process.cwd(), "public", "fonts");

// Chrome UA so the css2 endpoint serves woff2 rather than ttf.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

// `range` is the weight span the variable file covers and that Tome uses.
const FAMILIES = [
  { css: "Inter", name: "Inter", slug: "inter", range: "100..900", weight: "100 900" },
  { css: "Source+Serif+4", name: "Source Serif 4", slug: "source-serif-4", range: "200..900", weight: "200 900" },
  { css: "JetBrains+Mono", name: "JetBrains Mono", slug: "jetbrains-mono", range: "100..800", weight: "100 800" },
  { css: "Caveat", name: "Caveat", slug: "caveat", range: "400..700", weight: "400 700" },
];

/** Pull the `latin` @font-face block out of a Google Fonts css2 response. */
function latinFace(css) {
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
  let m;
  while ((m = re.exec(css))) if (m[1] === "latin") return m[2];
  return null;
}

async function main() {
  await rm(OUT, { recursive: true, force: true });
  await mkdir(OUT, { recursive: true });
  const out = [
    "/* Self-hosted type — generated by `node scripts/fetch-fonts.mjs`.",
    " * Families match Tome's app/layout.tsx next/font setup: Inter (sans),",
    " * Source Serif 4 (serif), JetBrains Mono (mono), Caveat (hand).",
    " * Variable woff2, latin subset. No request leaves the site. */",
    "",
  ];

  for (const fam of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${fam.css}:wght@${fam.range}&display=swap`;
    const css = await fetch(url, { headers: { "User-Agent": UA } }).then((r) => {
      if (!r.ok) throw new Error(`${url} → ${r.status}`);
      return r.text();
    });
    const face = latinFace(css);
    if (!face) throw new Error(`${fam.css}: no latin @font-face in css2 response`);
    const src = /url\((https:[^)]+)\)/.exec(face);
    const uni = /unicode-range:\s*([^;}]+)/.exec(face);
    if (!src || !uni) throw new Error(`${fam.css}: malformed @font-face`);

    const file = `${fam.slug}.woff2`;
    const buf = Buffer.from(
      await fetch(src[1], { headers: { "User-Agent": UA } }).then((r) => {
        if (!r.ok) throw new Error(`${src[1]} → ${r.status}`);
        return r.arrayBuffer();
      }),
    );
    await writeFile(path.join(OUT, file), buf);

    out.push(
      "@font-face {",
      `  font-family: '${fam.name}';`,
      "  font-style: normal;",
      `  font-weight: ${fam.weight};`,
      "  font-display: swap;",
      `  src: url(./${file}) format('woff2');`,
      `  unicode-range: ${uni[1].trim()};`,
      "}",
      "",
    );
    console.log(`${file}  ${(buf.length / 1024).toFixed(1)} kB`);
  }

  await writeFile(path.join(OUT, "fonts.css"), out.join("\n"));
  const files = (await readdir(OUT)).sort();
  console.log(`\npublic/fonts/: ${files.join(", ")}`);
}

main();
